hamster_hub_homepage:
    path:     /
    defaults: { _controller: HamsterHubBundle:Default:index }

video_upload:
    path: /video/upload
    defaults: { _controller: HamsterHubBundle:Video:upload }
    methods: [post]

video_delete:
    path: /video/delete
    defaults:  { _controller: HamsterHubBundle:Video:delete }
    methods: [post]
show_video:
      path:     /video/{videoId}
      defaults: { _controller: HamsterHubBundle:Video:index }
my_video:
      path: /myVideo/{userName}
      defaults: { _controller: HamsterHubBundle:Video:myvideo }
